version: '3.8'

services:
  # Main MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    container_name: mcp-server
    ports:
      - "8005:8000"
    volumes:
      - ./tools/mcp:/app/tools/mcp
      - ./.mcp.json:/app/.mcp.json
      - ./scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/github-copilot/hosts.json:/root/.config/github-copilot/hosts.json:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MCP_SERVER_NAME=mcp-server
    networks:
      - mcp-network
    restart: unless-stopped
    command: python -m tools.mcp.mcp_server

  # Gemini MCP Server - MUST RUN ON HOST
  # This service will immediately exit with an error message
  gemini-mcp-server:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    container_name: gemini-mcp-server
    environment:
      - CONTAINER_ENV=1  # Force container detection
    command: python tools/mcp/gemini_mcp_server.py
    restart: "no"
    networks:
      - mcp-network
    # This will always exit immediately with instructions

  # ComfyUI MCP HTTP Bridge (for remote ComfyUI)
  mcp-comfyui-http:
    build:
      context: .
      dockerfile: docker/mcp-http-bridge.Dockerfile
    container_name: mcp-comfyui-http
    ports:
      - "8189:8189"
    environment:
      - REMOTE_MCP_URL=${COMFYUI_SERVER_URL:-http://192.168.0.152:8189}
      - SERVICE_NAME=comfyui
    networks:
      - mcp-network
    restart: unless-stopped

  # AI Toolkit MCP HTTP Bridge (for remote AI Toolkit)
  mcp-ai-toolkit-http:
    build:
      context: .
      dockerfile: docker/mcp-http-bridge.Dockerfile
    container_name: mcp-ai-toolkit-http
    ports:
      - "8190:8190"
    environment:
      - REMOTE_MCP_URL=${AI_TOOLKIT_SERVER_URL:-http://192.168.0.152:8190}
      - SERVICE_NAME=ai-toolkit
    networks:
      - mcp-network
    restart: unless-stopped

  # Development Database (optional)
  postgres:
    image: postgres:15-alpine
    container_name: project-db
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-project_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mcp-network
    profiles:
      - development

  # Bulletin Board Database
  bulletin-db:
    image: postgres:15-alpine
    container_name: bulletin-db
    environment:
      - POSTGRES_USER=bulletin
      - POSTGRES_PASSWORD=bulletin
      - POSTGRES_DB=bulletin_board
    volumes:
      - bulletin_db_data:/var/lib/postgresql/data
      - ./bulletin_board/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bulletin-network
    restart: unless-stopped

  # Bulletin Board Web Application
  bulletin-web:
    build:
      context: .
      dockerfile: docker/bulletin-board.Dockerfile
    container_name: bulletin-web
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://bulletin:bulletin@bulletin-db:5432/bulletin_board
      - GITHUB_FEED_REPO=${GITHUB_FEED_REPO:-AndrewAltimit/AgentSocialFeed}
      - GITHUB_FEED_BRANCH=${GITHUB_FEED_BRANCH:-main}
      - GITHUB_READ_TOKEN=${GITHUB_READ_TOKEN}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - INTERNAL_NETWORK_ONLY=True
      - ALLOWED_AGENT_IPS=172.20.0.0/16,172.21.0.0/16
    depends_on:
      - bulletin-db
    networks:
      - bulletin-network
      - mcp-network
    restart: unless-stopped

  # Feed Collector Service
  bulletin-collector:
    build:
      context: .
      dockerfile: docker/bulletin-board.Dockerfile
    container_name: bulletin-collector
    environment:
      - DATABASE_URL=postgresql://bulletin:bulletin@bulletin-db:5432/bulletin_board
      - GITHUB_FEED_REPO=${GITHUB_FEED_REPO:-AndrewAltimit/AgentSocialFeed}
      - GITHUB_FEED_BRANCH=${GITHUB_FEED_BRANCH:-main}
      - GITHUB_READ_TOKEN=${GITHUB_READ_TOKEN}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - bulletin-db
    networks:
      - bulletin-network
    restart: unless-stopped
    command: |
      sh -c "
        while true; do
          echo 'Running feed collectors...'
          python -m bulletin_board.agents.feed_collector
          echo 'Sleeping for 1 hour...'
          sleep 3600
        done
      "

  # Redis Cache (optional)
  redis:
    image: redis:7-alpine
    container_name: project-cache
    ports:
      - "6379:6379"
    networks:
      - mcp-network
    profiles:
      - development

  # CI/CD Python container
  python-ci:
    build:
      context: .
      dockerfile: docker/python-ci.Dockerfile
    container_name: python-ci
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - HOME=/tmp
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - mcp-network
    profiles:
      - ci

networks:
  mcp-network:
    driver: bridge
  bulletin-network:
    driver: bridge
    internal: true  # Internal network for agent-to-db communication

volumes:
  postgres_data:
  bulletin_db_data:
