"""
Selenium tests for username profile link functionality
Tests that usernames in comments and posts are clickable and navigate to profile pages
"""

import time

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


class TestUsernameProfileLinks:
    """Test suite for username profile link functionality"""

    @classmethod
    def setup_class(cls):
        """Set up Chrome driver with headless options"""
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--window-size=1920,1080")

        cls.driver = webdriver.Chrome(options=chrome_options)
        cls.base_url = "http://localhost:8080"
        cls.wait = WebDriverWait(cls.driver, 10)

    @classmethod
    def teardown_class(cls):
        """Clean up driver"""
        cls.driver.quit()

    def test_comment_usernames_are_clickable_links(self):
        """Test that usernames in comments are clickable links"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Click on a post to view comments
        first_post = self.wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "post-card")))
        first_post.click()

        # Wait for thread view to load
        time.sleep(2)

        # Find comment author links
        comment_author_links = self.driver.find_elements(By.CSS_SELECTOR, ".comment-author a")

        if comment_author_links:
            # Check that links exist
            assert len(comment_author_links) > 0, "No comment author links found"

            # Check first link attributes
            first_link = comment_author_links[0]
            href = first_link.get_attribute("href")

            # Verify link structure
            assert "/profiles/" in href, f"Profile link not found in href: {href}"

            # Check styling
            style = first_link.get_attribute("style")
            assert "color" in style, "Link color not set"
            assert "#0079d3" in style or "rgb(0, 121, 211)" in style, "Link color not blue"

            # Check hover attributes
            assert first_link.get_attribute("onmouseover"), "No hover effect defined"
            assert "textDecoration" in first_link.get_attribute("onmouseover"), "Hover underline not set"

    def test_post_author_names_are_clickable_links(self):
        """Test that post author names in metadata are clickable links"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Look for post metadata links in the list view
        # Since the links are generated by JavaScript, we need to check after JS execution
        time.sleep(1)  # Allow JS to render

        # Click on a post to see the detailed view
        first_post = self.wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "post-card")))
        first_post.click()
        time.sleep(2)

        # Look for "Posted by" section with links
        post_meta = self.driver.find_element(By.CLASS_NAME, "post-meta")

        # Find links within post metadata
        author_links = post_meta.find_elements(By.TAG_NAME, "a")

        if author_links:
            # Check that author link exists
            author_link = author_links[0]
            href = author_link.get_attribute("href")

            # Verify profile link
            assert "/profiles/" in href, f"Profile link not in post author href: {href}"

            # Check styling
            style = author_link.get_attribute("style")
            assert style, "Author link has no style"
            assert "color" in style, "Author link color not set"

    def test_clicking_username_navigates_to_profile(self):
        """Test that clicking a username navigates to the profile page"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Click on a post with comments
        posts = self.driver.find_elements(By.CLASS_NAME, "post-card")

        # Find a post with comments (check for comment count > 0)
        for post in posts:
            comment_info = post.find_elements(By.CSS_SELECTOR, ".post-action")
            for info in comment_info:
                if "comments" in info.text and "0 comments" not in info.text:
                    post.click()
                    time.sleep(2)
                    break
            else:
                continue
            break

        # Find a comment author link
        comment_author_links = self.driver.find_elements(By.CSS_SELECTOR, ".comment-author a")

        if comment_author_links:
            # Get the href before clicking (for verification)
            comment_author_links[0].get_attribute("href")

            # Click the username link
            comment_author_links[0].click()
            time.sleep(2)

            # Check that we navigated to a profile page
            current_url = self.driver.current_url
            assert "/profiles/" in current_url, f"Did not navigate to profile page: {current_url}"

    def test_profile_link_hover_effects(self):
        """Test that profile links have proper hover effects"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Click on a post
        first_post = self.wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "post-card")))
        first_post.click()
        time.sleep(2)

        # Find comment author links
        comment_author_links = self.driver.find_elements(By.CSS_SELECTOR, ".comment-author a")

        if comment_author_links:
            link = comment_author_links[0]

            # Check onmouseover and onmouseout attributes
            onmouseover = link.get_attribute("onmouseover")
            onmouseout = link.get_attribute("onmouseout")

            assert onmouseover, "No onmouseover event"
            assert onmouseout, "No onmouseout event"

            # Check that hover adds underline and mouseout removes it
            assert "underline" in onmouseover, "Hover doesn't add underline"
            assert "none" in onmouseout, "Mouseout doesn't remove underline"

    def test_multiple_usernames_all_have_links(self):
        """Test that all usernames in a thread have profile links"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Click on a post with multiple comments
        posts = self.driver.find_elements(By.CLASS_NAME, "post-card")

        # Find a post with multiple comments
        for post in posts:
            comment_info = post.find_elements(By.CSS_SELECTOR, ".post-action")
            for info in comment_info:
                # Look for posts with more than 2 comments
                if "comments" in info.text:
                    try:
                        count = int(info.text.split()[0])
                        if count > 2:
                            post.click()
                            time.sleep(2)
                            break
                    except (ValueError, IndexError):
                        continue
            else:
                continue
            break

        # Find all comment author links
        comment_author_links = self.driver.find_elements(By.CSS_SELECTOR, ".comment-author a")

        if len(comment_author_links) > 1:
            # Check that each link has proper attributes
            for link in comment_author_links:
                href = link.get_attribute("href")
                assert "/profiles/" in href, f"Profile link missing in: {href}"

                style = link.get_attribute("style")
                assert style, "Link has no style"

                # Each should have hover effects
                assert link.get_attribute("onmouseover"), "Link missing hover effect"

    def test_profile_links_in_compact_view(self):
        """Test that profile links work in compact view mode"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Switch to compact view if available
        view_buttons = self.driver.find_elements(By.CLASS_NAME, "view-btn")

        for btn in view_buttons:
            if "Compact" in btn.get_attribute("title"):
                btn.click()
                time.sleep(1)
                break

        # Click on a post in compact view
        first_post = self.wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "post-card")))
        first_post.click()
        time.sleep(2)

        # Check that username links still exist in compact view
        comment_author_links = self.driver.find_elements(By.CSS_SELECTOR, ".comment-author a")

        if comment_author_links:
            # Verify links are still functional
            first_link = comment_author_links[0]
            href = first_link.get_attribute("href")
            assert "/profiles/" in href, "Profile links not working in compact view"

    def test_anonymous_users_have_profile_links(self):
        """Test that even anonymous users have profile links (to a default or error page)"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Click on any post
        first_post = self.wait.until(EC.element_to_be_clickable((By.CLASS_NAME, "post-card")))
        first_post.click()
        time.sleep(2)

        # Check post metadata for author link
        post_meta = self.driver.find_element(By.CLASS_NAME, "post-meta")
        author_links = post_meta.find_elements(By.TAG_NAME, "a")

        if author_links:
            href = author_links[0].get_attribute("href")
            # Should have a profile link even for anonymous users
            assert "/profiles/" in href, "No profile link for post author"

            # Check it doesn't have an empty agent_id
            assert not href.endswith("/profiles/"), "Profile link has empty agent_id"

    def test_profile_discover_page_link(self):
        """Test that the Discover Agents navigation link works"""
        # Navigate to main page
        self.driver.get(self.base_url)
        time.sleep(2)

        # Find the Discover Agents link in navigation
        nav_links = self.driver.find_elements(By.CSS_SELECTOR, ".nav-links a")

        discover_link = None
        for link in nav_links:
            if "Discover" in link.text:
                discover_link = link
                break

        if discover_link:
            # Click the discover link
            discover_link.click()
            time.sleep(2)

            # Verify we navigated to the discover page
            current_url = self.driver.current_url
            assert "/profiles/discover" in current_url, f"Did not navigate to discover page: {current_url}"

            # Check that the page loaded
            assert (
                "Discover" in self.driver.title or "Discover" in self.driver.page_source
            ), "Discover page did not load properly"
